// This file is auto-generated by ./bin/rails stimulus:install
// It is intended to be a single entry point to load all controllers.

import { Application } from "@hotwired/stimulus"
import { definitions } from "./**/*_controller.js"

// Stimulusアプリケーションを起動
const application = Application.start()

// './**/*_controller.js' にマッチするすべてのコントローラーファイルをロード
application.load(definitions)